<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile
?>
<img src="<?php echo $block->getSellerStatisticsGraphUrl(true) ?>" alt="Top Selling Country" title="Top Selling Country" id="wk-location-chart"/>