<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Feed
 */
?>
<?php
/** @var \Amasty\Feed\Block\Adminhtml\Category\Edit\Tab\ExcludeMapping $block */
$_value = $block->getElement()->getValue();
$_htmlId = $block->getElement()->getHtmlId();
?>
<div class="field" id="attribute-<?= $block->escapeHtml($_htmlId) ?>-container">
    <label class="label"><?= $block->escapeHtml($block->getElement()->getLabel()); ?></label>
    <div class="control">
        <ul class="amfeed-exclude-categories">
            <?php foreach ($block->getCategoriesList() as $category) : ?>
                <li class="amfeed-category" style="padding-left: <?= ($category['level'] * 30) ?>px;">
                    <input  class="amfeed-checkbox"
                            data-amfeed-js="category-<?= $block->escapeHtml($category['id']) ?>"
                            type="checkbox"
                            title="<?= $block->escapeHtml(__('Ignore category')) ?>"
                            name="mapping[<?= $block->escapeHtml($category['id']) ?>][skip]"
                            value="1"
                            id="exclude-category-<?= $block->escapeHtml($category['id']) ?>"
                        <?php if (isset($_value[$category['id']]['skip']) && $_value[$category['id']]['skip']) : ?>
                            checked="checked"
                        <?php endif; ?>
                            onclick="mappingControl.disableCategory(this)"
                    />
                    <label class="amfeed-label" for="exclude-category-<?= $category['id'] ?>">
                        <?= $block->escapeHtml($category['name']); ?>
                    </label>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<script>
    require([
        'jquery'
    ], function ($) {
        var mappingControl = {
            disableCategory: function (elem) {
                var input = $('[data-amfeed-js="amfeed-taxonomy-input"].' + elem.getAttribute('data-amfeed-js'));
                if (elem.checked) {
                    input.parents('[data-amfeed-js="category-item"]').hide();
                    input.removeClass('required-entry _required')
                } else {
                    input.parents('[data-amfeed-js="category-item"]').show();
                    input.addClass('required-entry _required');
                }
            }
        };

        window.mappingControl = mappingControl;
    });
</script>
