<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

$containerId = $block->getContainerId();
$title = $block->getTitle();
$subtitle = $block->getSubtitle();
$orderQty30days = $block->getOrderQty30days();
$itemQty30days = $block->getItemQty30days();
$revenue30days = $block->getRevenue30days();
$currencySymbol = $block->getCurrencySymbol();
?>
<?php if($containerId): ?>
    <script type="text/javascript">
        require([
            "jquery",
            "Magestore_InventorySuccess/js/chart/highcharts",
            "Magestore_InventorySuccess/js/chart/data",
            "Magestore_InventorySuccess/js/chart/exporting"
        ], function($){
            $(function () {
                var container = '#' + '<?php echo $containerId ?>';
                var d = new Date();
                var m = d.getMonth();
                d.setMonth(d.getMonth() - 1);
                d.setDate(d.getDate() - 2);
                if (d.getMonth() === m)
                    d.setDate(0);
                d.setHours(0, 0, 0);
                $(container).highcharts({
                    chart: {
                        type: 'line',
                        zoomType: 'xy'
                    },
                    plotOptions: {
                        series: {
                            marker: {
                                enabled: false
                            }
                        }
                    },
                    title: {
                        text: '<?php echo $title; ?>'
                    },

                    subtitle: {
                        text: '<?php echo $subtitle; ?>'
                    },
                    xAxis: {
                        tickInterval: 7 * 24 * 3600 * 1000, // one week
                        gridLineWidth: 1,
                        labels: {
                            align: 'left',
                            x: 3,
                            y: -3
                        },
                        type: 'datetime',
                        dateTimeLabelFormats: {
                            day: '%e of %b'
                        },
                        crosshair: true
                    },
                    yAxis:  [{
                            labels: {
                                format: '{value}',
                                style: {
                                    color: Highcharts.getOptions().colors[1]
                                }
                            },
                            title: {
                                text: '<?php echo __('Products Ordered & Qty Ordered') ?>',
                                style: {
                                    color: Highcharts.getOptions().colors[1]
                                }
                            }
                        }, {// Secondary yAxis
                            title: {
                                text: '<?php echo __('Revenue') ?>',
                                style: {
                                    color: Highcharts.getOptions().colors[0]
                                }
                            },
                            labels: {
                                format: '<?php echo $currencySymbol ?>{value}',
                                style: {
                                    color: Highcharts.getOptions().colors[0]
                                }
                            },
                            opposite: true
                    }],
                    tooltip: {
                        shared: true,
                        crosshairs: true
                    },
                    legend: {
                        enable: true,
                        align: 'center',
                        verticalAlign: 'bottom',
                        y: 20,
                        floating: true,
                        borderWidth: 0
                    },
                    series: [{
                        name: 'Products Ordered',
                        type: 'spline',
                        data: [<?php echo $orderQty30days; ?>],
                        pointStart: Date.UTC(d.getFullYear(), d.getMonth() , d.getDate()),//pointStart: Date.UTC(d.getYear(), d.getMonth(), d.getDate()),
                        pointInterval: 24 * 3600 * 1000, // one day
                        lineWidth: 4,
                        marker: {
                            radius: 4
                        },
                        tooltip: {
                            valueSuffix: '<?php //echo __(' Orders') ?>'
                        }
                    },{
                        name: 'Qty Ordered',
                        type: 'spline',
                        data: [<?php echo $itemQty30days; ?>],
                        pointStart: Date.UTC(d.getFullYear(), d.getMonth() , d.getDate()),//pointStart: Date.UTC(d.getYear(), d.getMonth(), d.getDate()),
                        pointInterval: 24 * 3600 * 1000, // one day
                        lineWidth: 4,
                        marker: {
                            radius: 4
                        }
                    }, {
                        name: 'Revenue',
                        type: 'spline',
                        yAxis: 1,
                        data: [<?php echo $revenue30days; ?>],
                        pointStart: Date.UTC(d.getFullYear(), d.getMonth() , d.getDate()),//pointStart: Date.UTC(d.getYear(), d.getMonth(), d.getDate()),
                        pointInterval: 24 * 3600 * 1000, // one day
                        tooltip: {
                            valuePrefix: '<?php echo $currencySymbol ?>'
                        }
                    }]
                });
            });
        })
    </script>
<?php endif ?>
