<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /** @var $block \Magento\Bundle\Block\Adminhtml\Sales\Order\Items\Renderer */ ?>

<?php $_item = $block->getItem() ?>
<?php $_parentItem = $_item ?>
<?php $items = $block->getChildren($_item); ?>
<?php $_count = count($items) ?>
<?php $_index = 0 ?>

<?php $_prevOptionId = '' ?>

<?php if ($block->getOrderOptions() || $_item->getDescription()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>
<?php $parentQty = 1; ?>
<?php foreach ($items as $_item): ?>
    <?php $block->setPriceDataObject($_item) ?>
    <?php if ($_item->getOrderItem()->getParentItem()): ?>
        <?php $attributes = $block->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
        <tr>
            <td class="col-product"><div class="option-label"><?php /* @escapeNotVerified */ echo $attributes['option_label'] ?></div></td>
            <td class="col-product">&nbsp;</td>
            <td class="col-qty last">&nbsp;</td>
        </tr>
        <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php else: ?>
        <?php $parentQty = $_item->getQty() ?>        
    <?php endif; ?>
    <?php $qtyInputClass = $_item->getOrderItem()->getParentItem() ? 'bundle-child-qty-to-ship-input'.$_parentItem->getOrderItemId() : 'bundle-qty-to-ship-input' ; ?>        
    <tr class="<?php echo(++$_index == $_count && !$_showlastRow) ? 'border' : '' ?>">
        <?php if (!$_item->getOrderItem()->getParentItem()): ?>
        <td class="col-product">
            <div class="product-title"><?php echo $block->escapeHtml($_item->getName()) ?></div>
            <div class="product-sku-block">
                <span><?php /* @escapeNotVerified */ echo __('SKU') ?>:</span>
                <?php echo implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($_item->getSku()))); ?>
            </div>
        </td>
        <?php else: ?>
        <td class="col-product"><div class="option-value"><?php echo $block->getValueHtml($_item)?></div></td>
        <?php endif; ?>   
        <td class="col-ordered-qty">
            <?php if ($block->isShipmentSeparately($_item) || $_item->getOrderItem()->getParentItem()): ?>
                <?php echo $block->getColumnHtml($_item, 'qty') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-qty-in-warehouse" id="qty_in_warehouse[<?php echo $_item->getOrderItemId() ?>]"></td>             
        <td class="col-qty">
            <?php if ($block->isShipmentSeparately($_item)): ?>
                <input type="text"
                       class="input-text admin__control-text qty-to-ship-input <?php echo $qtyInputClass ?>"
                       name="shipment[items][<?php /* @escapeNotVerified */ echo $_item->getOrderItemId() ?>]"
                       id="shipment[items][<?php /* @escapeNotVerified */ echo $_item->getOrderItemId() ?>]"
                       value="<?php /* @escapeNotVerified */ echo $_item->getQty()*1 ?>" />
            <?php elseif($_item->getOrderItem()->getParentItem()): ?>
                <input type="text"
                       class="input-text admin__control-text qty-to-ship-input <?php echo $qtyInputClass ?>"
                       name="shipment[items][<?php /* @escapeNotVerified */ echo $_item->getOrderItemId() ?>]"
                       id="shipment[items][<?php /* @escapeNotVerified */ echo $_item->getOrderItemId() ?>]"
                       value="<?php /* @escapeNotVerified */ echo $this->getBundleQty($_item) * $parentQty ?>" 
                       readonly="readonly"/>
                <input type="hidden" 
                       value="<?php echo $this->getBundleQty($_item) ?>" 
                       id="shipment[bundle_qty][<?php /* @escapeNotVerified */ echo $_item->getOrderItemId() ?>]"/>
            <?php endif; ?>
        </td>
        <?php if ($block->isShipmentSeparately($_item) || 1): ?>
        <td class="col-qty-pending-ship last" id="qty_pending_ship[<?php echo $_item->getOrderItemId()?>]"></td>
        <?php else: ?>
        <td class="last"></td>
        <?php endif; ?>
    
    </tr>
<?php endforeach; ?>
<?php if ($_showlastRow): ?>
    <tr class="border">
        <td class="col-product">
            <?php if ($block->getOrderOptions($_item->getOrderItem())): ?>
                <dl class="item-options">
                <?php foreach ($block->getOrderOptions($_item->getOrderItem()) as $option): ?>
                    <dt><?php /* @escapeNotVerified */ echo $option['label'] ?></dt>
                    <dd>
                    <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                        <?php /* @escapeNotVerified */ echo $option['value'];?>
                    <?php else: ?>
                        <?php echo $block->truncateString($option['value'], 55, '', $_remainder);?>
                        <?php if ($_remainder):?>
                            ... <span id="<?php /* @escapeNotVerified */ echo $_id = 'id' . uniqid()?>"><?php /* @escapeNotVerified */ echo $_remainder ?></span>
                            <script>
require(['prototype'], function(){

                            $('<?php /* @escapeNotVerified */ echo $_id ?>').hide();
                            $('<?php /* @escapeNotVerified */ echo $_id ?>').up().observe('mouseover', function(){$('<?php /* @escapeNotVerified */ echo $_id ?>').show();});
                            $('<?php /* @escapeNotVerified */ echo $_id ?>').up().observe('mouseout',  function(){$('<?php /* @escapeNotVerified */ echo $_id ?>').hide();});

});
</script>
                        <?php endif;?>
                    <?php endif;?>
                    </dd>
                <?php endforeach; ?>
                </dl>
                        <?php else: ?>
                &nbsp;
                        <?php endif; ?>
            <?php echo $block->escapeHtml($_item->getDescription()) ?>
        </td>
        <td class="col-ordered-qty">&nbsp;</td>
        <td class="col-qty">&nbsp;</td>
        <td class="col-qty-in-warehouse">&nbsp;</td>        
        <td class="col-qty-pending-ship last">&nbsp;</td>
    </tr>
<?php endif; ?>
