<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magestore\InventorySuccess\Block\Adminhtml\Order\Creditmemo\Create\Items\Column\Warehouse */ ?>
<?php $warehouses = $block->getAvailableWarehouses() ?>
<?php if ($_item = $block->getItem()): ?>
    <?php $requireClass = $block->isRequired($_item) ? 'required-entry _required' : '' ?>
    <?php if($this->isShow($_item)): ?>
        <select class="admin__control-select <?php echo $requireClass ?> return-warehouse-select"
                name="creditmemo[items][<?php /* @escapeNotVerified */ echo $_item->getItemId() ?>][warehouse]"
                id="creditmemo[items][<?php /* @escapeNotVerified */ echo $_item->getItemId() ?>][warehouse]">
            <!--            <option value="">--><?php ///* @escapeNotVerified */ echo __('Select Warehouse')?><!--</option>-->
            <?php if(count($warehouses)): ?>
                <?php foreach($warehouses as $warehouseId => $warehouseName): ?>
                    <option value="<?php echo $warehouseId ?>"
                        <?php if($this->isSelectedWarehouse($warehouseId, $_item->getItemId()) || count($warehouses) == 1) echo 'selected="selected"' ?>>
                        <?php echo $warehouseName ?>
                    </option>
                <?php endforeach; ?>
            <?php endif; ?>
        </select>
        <input type="text" class="input-text admin__control-text not-return-reason"
               style="display:none;"
               placeholder="<?php echo __('Why don\'t return items to stock?') ?>"
               name="creditmemo[items][<?php /* @escapeNotVerified */ echo $_item->getItemId() ?>][reason]"
               id="creditmemo[items][<?php /* @escapeNotVerified */ echo $_item->getItemId() ?>][reason]">
        <input type="hidden" class="order-item-qty-to-ship" value="<?php echo $_item->getQtyToShip() ?>"/>
        <?php
        $parentItem = $_item->getParentItem();
        if ($parentItem && $parentItem->getProductType() == \Magento\Bundle\Model\Product\Type::TYPE_CODE && $parentItem->getProduct()->getShipmentType() == '0'){
            $qtyToShip = $_item->getQtyOrdered() / $parentItem->getQtyOrdered() * ($parentItem->getQtyOrdered() - $parentItem->getQtyShipped()) - $_item->getQtyCanceled() - $_item->getQtyRefunded();
        } else {
            $qtyToShip = $_item->getQtyToShip();
        }
        ?>
        <div class="product-sku-block" id="real_return_item_<?php /* @escapeNotVerified */ echo $_item->getItemId() ?>" qtyToShip="<?php echo $qtyToShip ?>"></div>
    <?php endif; ?>
<?php endif; ?>
