<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

$containerId = $block->getContainerId();
    $title = $block->getTitle();
    $subtitle = $block->getSubtitle();
    $xAxisTitle = $block->getXAxisTitle();
    $yAxisTitle = $block->getYAxisTitle();
    $tooltip = $block->getTooltip();
    $seriesName = $block->getSeriesName();
    $seriesType = $block->getSeriesType();
    $seriesData = $block->getSeriesData();
    $seriesDataLabel = $block->getSeriesDataLabel();
?>
<?php if($containerId): ?>
    <script type="text/javascript">
        require([
            "jquery",
            "Magestore_InventorySuccess/js/chart/highcharts",
            "Magestore_InventorySuccess/js/chart/exporting"
        ], function($){
            var container = '#' + '<?php echo $containerId ?>';
            $(function () {
                $(container).highcharts({
                    chart: {
                        type: 'column'
                    },
                    title: {
                        text: '<?php echo $title; ?>'
                    },
                    subtitle: {
                        text: '<?php echo $subtitle; ?>'
                    },
                    xAxis: {
                        type: 'category',
                        labels: {
                            rotation: -45,
                            style: {
                                fontSize: '13px',
                                fontFamily: 'Verdana, sans-serif'
                            }
                        },
                        title: {
                            text: '<?php echo $xAxisTitle; ?>'
                        }
                    },
                    yAxis: {
                        min: 0,
                        title: {
                            text: '<?php echo $yAxisTitle; ?>'
                        }
                    },
                    legend: {
                        enabled: true
                    },
                    tooltip: {
                        pointFormat: '<?php echo $tooltip ?>'
                    },
                    series: [
                        <?php for ($index = 0; $index < count($seriesName); $index++): ?>
                        {
                            name: '<?php echo $seriesName[$index]; ?>',
                            type: 'column',
                            data: [
                                <?php foreach ($seriesData[$index] as $item): ?>
                                ["<?php echo $item[0]; ?>", <?php echo $item[1]; ?>],
                                <?php endforeach; ?>
                            ],
                            dataLabels: {
                                enabled: true,
                                rotation: -90,
                                color: '#FFFFFF',
                                align: 'right',
                                format: '<?php echo $seriesDataLabel[$index]['format']; ?>', // one decimal
                                y: 10, // 10 pixels down from the top
                                style: {
                                    fontSize: '13px',
                                    fontFamily: 'Verdana, sans-serif'
                                }
                            }
                        }
                        <?php endfor; ?>
                    ]
                });
            });
        })
        
    </script>
<?php endif ?>
