<table cellspacing="0" class="form-list">
    <tbody>
        <tr>
            <td class="label">
                <label>
                    <span>Progress</span>
                </label>
            </td>
            <td class="value">
                <progress id="po_image_status_progress_bar" value="<?php echo $block->getProgressPercentValue() ?>" max="100"></progress>
                <div class="po-image-status-progress-result"><?php echo __("%1% done (%2 images from %3 are optimized)", $block->getProgressPercentValue(), $block->getOptimizedCount(), $block->getTotalCount())?></div>
            </td>
        </tr>
        <tr>
            <td class="label">
                <label>
                    <span>Errors</span>
                </label>
            </td>
            <td class="value">
                <div class="<?php echo count($block->getErrorByGroup()) === 0 ? 'status-success-value' : 'status-error-value' ?>">
                    <?php echo __("%1 error(s) found", count($block->getErrorByGroup()))?>
                </div>
                <ul class="status-error-group-list">
                    <?php foreach ($block->getErrorByGroup() as $errorType): ?>
                        <li>
                            <?php echo $errorType['text'] ?>
                            <a href="<?php echo $block->getErrorUrlByCode($errorType['code'])?>"><?php echo __("%1 image(s)", $errorType['count'])?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </td>
        </tr>
    </tbody>
</table>