<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Feed
 */
?>
<?php
$countOfSteps = 3;
$stepTitles = ['Initialising', 'In Progress', 'Success'];
?>
<ul class="amsteps-icons-wrapper">
    <?php for ($stepNumber = 1; $stepNumber <= $countOfSteps; $stepNumber++) : ?>
        <li class="amsteps-icon" data-amsteps-js="step-<?= $stepNumber ?>"></li>
    <?php endfor; ?>
</ul>
<ul class="amsteps-titles-wrapper">
    <?php foreach ($stepTitles as $stepNumber => $title) : ?>
        <li class="amsteps-title" data-amsteps-js="step-title-<?= $stepNumber + 1 ?>">
            <?= $block->escapeHtml(__($title)); ?>
        </li>
    <?php endforeach; ?>
</ul>
