<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Feed
 */
?>
<div class="amprogressbar-progress-timer">
    <div class="amprogressbar-progress-container">
        <div class="amprogressbar-progress-wrapper">
            <progress max="100" value="0" class="amprogressbar-progress" data-amprogressbar-js="bar"></progress>
        </div>
        <span class="amprogressbar-percentage" data-amprogressbar-js="progressbar-value"></span>
    </div>
    <span class="amprogressbar-clock"></span>
    <strong class="amprogressbar-time" data-amprogressbar-js="timer"></strong>
</div>
