<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Feed
 */
?>
<?php
/** @var \Amasty\Feed\Block\Adminhtml\Feed\Edit\Tab\Csv\Field $block */
$_value       = $block->getElement()->getCsvField();
$_htmlId      = $block->getElement()->getHtmlId();
$_htmlClass   = $block->getElement()->getClass();
$_htmlName    = $block->getElement()->getName();
$_readonly    = $block->getElement()->getReadonly();
?>
<div class="field" id="attribute-<?= $_htmlId ?>-container">
    <div class="control">
        <table class="admin__control-table amasty-csv-table" id="fields_table">
            <thead>
            <tr>
                <th class="required"><?= __('Header') ?></th>
                <th class="required"><?= __('Attribute') ?></th>
                <th class="required"><?= __('Format') ?></th>
                <th class="required"><?= __('Parent') ?></th>
                <th>&nbsp;</th>
            </tr>
            </thead>
            <tbody id="<?= $_htmlId; ?>_container"></tbody>
            <tfoot>
            <tr>
                <td colspan="6" class="col-actions-add"><?= $block->getAddAttributeButtonHtml(); ?>&nbsp;<?= $block->getAddStaticTextButtonHtml(); ?></td>
            </tr>
            </tfoot>
        </table>
    </div>
</div>
<script>
    require([
        'mage/template',
        'prototype',
        'mage/adminhtml/form'
    ], function (mageTemplate) {
        //<![CDATA[
            var fieldRowTemplate = '<tr>'
            + '<td><input id="field_row_<%- data.index %>_header" name="<?= $_htmlName; ?>[<%- data.index %>][header]" class="<?= $_htmlClass; ?> required-entry"/></td>'
            + '<td><select id="field_row_<%- data.index %>_attribute" class="<?= $_htmlClass; ?> required-entry" name="<?= $_htmlName; ?>[<%- data.index %>][attribute]" >'
            + '<optgroup label="<?= __("Basic"); ?>">'
            <?php foreach ($block->getBasicAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?= $_attributeId; ?>"><?= $block->escapeOption($_attributeName); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?= __("Advanced"); ?>">'
            <?php foreach ($block->getAdvancedAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?= $_attributeId; ?>"><?= $block->escapeOption($_attributeName); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?= __("Product"); ?>">'
            <?php foreach ($block->getProductAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?= $_attributeId; ?>"><?= $block->escapeOption($_attributeName); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?= __("Inventory"); ?>">'
            <?php foreach ($block->getInventoryAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?= $_attributeId; ?>"><?= $block->escapeOption($_attributeName); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?= __("Price"); ?>">'
            <?php foreach ($block->getPriceAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?= $_attributeId; ?>"><?= $block->escapeOption($_attributeName); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?= __("Category"); ?>">'
            <?php foreach ($block->getCategoryAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?= $_attributeId; ?>"><?= $block->escapeOption($_attributeName); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?= __("Category Paths"); ?>">'
            <?php foreach ($block->getCategoryPathsAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?= $_attributeId; ?>"><?= $block->escapeOption($_attributeName); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?= __("Custom Fields"); ?>">'
            <?php foreach ($block->getCustomFieldsAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?= $_attributeId; ?>"><?= $block->escapeOption($_attributeName); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?= __("Image"); ?>">'
            <?php foreach ($block->getImageAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?= $_attributeId; ?>"><?= $block->escapeOption($_attributeName); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?= __("Gallery"); ?>">'
            <?php foreach ($block->getGalleryAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?= $_attributeId; ?>"><?= $block->escapeOption($_attributeName); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?= __("Url"); ?>">'
            <?php foreach ($block->getUrlAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?= $_attributeId; ?>"><?= $block->escapeOption($_attributeName); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '</select></td>'
            + '<td><select id="field_row_<%- data.index %>_format" class="<?= $_htmlClass; ?> required-entry" name="<?= $_htmlName; ?>[<%- data.index %>][format]" >'
            <?php foreach ($block->getFormats() as $_formatId => $_formatName): ?>
            + '<option value="<?= $_formatId; ?>"><?= $block->escapeOption($_formatName); ?></option>'
            <?php endforeach; ?>
            + '</select></td>'
            + '<td><select id="field_row_<%- data.index %>_parent" class="<?= $_htmlClass; ?> required-entry" name="<?= $_htmlName; ?>[<%- data.index %>][parent]" >'
            <?php foreach ($block->getYesNoVars() as $_formatId => $_formatName): ?>
            + '<option value="<?= $_formatId; ?>"><?= $block->escapeOption($_formatName); ?></option>'
            <?php endforeach; ?>
            + '</select></td>'
            + '<td class="col-delete"><input type="hidden" name="<?= $_htmlName; ?>[<%- data.index %>][delete]" class="delete" value="" id="field_row_<%- data.index %>_delete" />'
            + '<button title="<?= __('Delete'); ?>" type="button" class="action- scalable delete icon-btn delete-product-option" id="field_row_<%- data.index %>_delete_button" onclick="return fieldControl.deleteAttribute(event, <%- data.index %>);">'
            + '<span><?= __('Delete'); ?></span></button>'

            + '</td>'
            + '</tr>'
            + '<tr><td class="amasty-modify-cell" colspan=5><table id="field_row_<%- data.index %>_modify_container"></table>'
            + '<a id="amasty_modify_link_hide_<%- data.index %>" class="amasty-modify-link amasty-hide-link" href="#" onclick="fieldControl.hideModifiers(<%- data.index %>); return false;">'
            + '<?= __('hide modifier(s)'); ?>'
            + '</a>'
            + '<a id="amasty_modify_link_add_<%- data.index %>" class="amasty-modify-link" href="#" onclick="fieldControl.modifyItem(<%- data.index %>); return false;">'
            + '<?= __('add modifier'); ?>'
            + '</a>'
            + '<a id="amasty_modify_link_show_<%- data.index %>" class="amasty-modify-link" href="#" onclick="fieldControl.showModifiers(<%- data.index %>); return false;">'
            + '<?= __('show modifier(s)'); ?>'
            + '</a>'
            + '</td></tr>';

            var modifyTemplate = '<tr>'
            + '<td class="amasty-modify">'
            + '<select onchange="return fieldControl.changeModifier(this);" id="field_row_<%- data.rowIndex %>_<%- data.index %>_modify" class="<?= $_htmlClass; ?> required-entry" name="<?= $_htmlName; ?>[<%- data.rowIndex %>][modify][<%- data.index %>][modify]">'
            <?php foreach ($block->getModiftVars() as $_modifyId => $_modifyName): ?>
            + '<option value="<?= $_modifyId; ?>"><?= $block->escapeOption($_modifyName); ?></option>'
            <?php endforeach; ?>
            + '</select>'
            + '<input style="display: none;" id="field_row_<%- data.rowIndex %>_<%- data.index %>_arg0" name="<?= $_htmlName; ?>[<%- data.rowIndex %>][modify][<%- data.index %>][arg0]" class="<?= $_htmlClass; ?>"/>'
            + '<input style="display: none;" id="field_row_<%- data.rowIndex %>_<%- data.index %>_arg1" name="<?= $_htmlName; ?>[<%- data.rowIndex %>][modify][<%- data.index %>][arg1]" class="<?= $_htmlClass; ?>"/>'
            + '<button title="<?= __('Delete'); ?>" type="button" class="action- scalable delete icon-btn delete-product-option" id="field_row_<%- data.rowIndex %>_<%- data.index %>_delete_button" onclick="return fieldControl.deleteItem(event);" >'
            + '<span><?= __('Delete'); ?></span></button>'
            + '</td>'
            + '</tr>';

            var staticTextRowTemplate = '<tr>'
            + '<td><input id="field_row_<%- data.index %>_header" name="<?= $_htmlName; ?>[<%- data.index %>][header]" class="<?= $_htmlClass; ?> required-entry"/></td>'
            + '<td colspan=3><input id="field_row_<%- data.index %>_static_text" class="<?= $_htmlClass; ?> required-entry" name="<?= $_htmlName; ?>[<%- data.index %>][static_text]" />'
            + '</td>'
            + '<td class="col-delete"><input type="hidden" name="<?= $_htmlName; ?>[<%- data.index %>][delete]" class="delete" value="" id="field_row_<%- data.index %>_delete" />'
            + '<button title="<?= __('Delete'); ?>" type="button" class="action- scalable delete icon-btn delete-product-option" id="field_row_<%- data.index %>_delete_button" onclick="return fieldControl.deleteItem(event);">'
            + '<span><?= __('Delete'); ?></span></button>'
            + '</td>'
            + '</tr>';

        var fieldControl = {
            rowTemplate: mageTemplate(fieldRowTemplate),
            modifyTemplate: mageTemplate(modifyTemplate),
            staticTextRowTemplate: mageTemplate(staticTextRowTemplate),
            itemsCount: 0,
            modifyCount: 0,
            argsConfig: <?= json_encode($this->getArgs())?>,
            addItem: function (header, attribute, format, parent) {


                var data = {
                    index: this.itemsCount++
                };

                Element.insert($('<?= $_htmlId; ?>_container'), {
                    bottom: this.rowTemplate({
                        data: data
                    })
                });

                if (header)
                    $('field_row_' + data.index + '_header').value = header;

                if (attribute)
                    $('field_row_' + data.index + '_attribute').value = attribute;

                if (format)
                    $('field_row_' + data.index + '_format').value = format;

                if (parent)
                    $('field_row_' + data.index + '_parent').value = parent;

                var linkHide = $("amasty_modify_link_hide_" + data.index);
                var linkShow = $("amasty_modify_link_show_" + data.index);

                linkHide.hide();
                linkShow.hide();

                return data.index;

            },
            addStaticTextItem: function (header, text) {
                var data = {
                    index: this.itemsCount++
                };

                Element.insert($('<?= $_htmlId; ?>_container'), {
                    bottom: this.staticTextRowTemplate({
                        data: data
                    })
                });

                if (header)
                    $('field_row_' + data.index + '_header').value = header;

                if (text)
                    $('field_row_' + data.index + '_static_text').value = text;

                return data.index;
            },
            deleteAttribute: function (event, rowIndex) {
                $('field_row_' + rowIndex + '_modify_container').up('tr').remove();
                this.deleteItem(event);
            },
            deleteItem: function (event) {
                var tr = Event.findElement(event, 'tr');
                if (tr) {
                    Element.select(tr, ['input', 'select']).each(function (element) {
                        element.remove();
                    });
                    Element.remove(tr);
                }
                return false;
            },
            modifyItem: function (rowIndex, modify, arg0, arg1) {
                var containerId = 'field_row_' + rowIndex + '_modify_container';

                var container = $(containerId);
                var linkHide = $("amasty_modify_link_hide_" + rowIndex);
                var link = $("amasty_modify_link_" + rowIndex);

                if (container) {
                    var data = {
                        index: this.modifyCount++,
                        rowIndex: rowIndex
                    };

                    Element.insert(container, {
                        bottom: this.modifyTemplate({
                            data: data
                        })
                    });

                    if (modify) {
                        var modifySelect = $('field_row_' + data.rowIndex + '_' + data.index + '_modify');
                        if (modifySelect) {
                            modifySelect.value = modify;
                            this.changeModifier(modifySelect);
                        }
                    }

                    if (arg0) {
                        $('field_row_' + data.rowIndex + '_' + data.index + '_arg0').value = arg0;
                    }

                    if (arg1) {
                        $('field_row_' + data.rowIndex + '_' + data.index + '_arg1').value = arg1;
                    }

                    linkHide.show();
                }
            },
            changeModifier: function (select) {
                var td = select.up('td');

                var args = [];

                if (this.argsConfig[select.getValue()]) {
                    args = this.argsConfig[select.getValue()];
                }

                td.select('input').each(function (input) {
                    input.hide();
                });

                for (var idx = 0; idx < args.length; idx++) {
                    var id = select.id.replace("_modify", "_arg" + idx);
                    var input = td.down("#" + id);
                    if (input) {
                        input.show();
                        input.setAttribute('placeholder', args[idx]);
                    }
                }
            },
            showAddModifyLink: function (rowIndex) {
                var $linkAdd = $("amasty_modify_link_add_" + rowIndex);
                var $linkShow = $("amasty_modify_link_show_" + rowIndex);
                var $linkHide = $("amasty_modify_link_hide_" + rowIndex);
                var $container = $("field_row_" + rowIndex + "_modify_container");

                if ($container.select("tr").length > 0) {
                    $container.hide();
                    $linkShow.show();
                    $linkAdd.hide();
                    $linkHide.hide();

                } else {
                    $linkShow.hide();
                    $linkAdd.show();
                    $linkHide.hide();

                }

            },
            showModifiers: function (rowIndex) {
                var $linkAdd = $("amasty_modify_link_add_" + rowIndex);
                var $linkShow = $("amasty_modify_link_show_" + rowIndex);
                var $container = $("field_row_" + rowIndex + "_modify_container");
                var $linkHide = $("amasty_modify_link_hide_" + rowIndex);

                $linkShow.hide();
                $linkAdd.show();
                $linkHide.show();

                $container.show();
            },
            hideModifiers: function (rowIndex) {
                var $linkAdd = $("amasty_modify_link_add_" + rowIndex);
                var $linkShow = $("amasty_modify_link_show_" + rowIndex);
                var $container = $("field_row_" + rowIndex + "_modify_container");
                var $linkHide = $("amasty_modify_link_hide_" + rowIndex);

                $linkShow.show();
                $linkAdd.hide();
                $linkHide.hide();

                $container.hide();
            }
        };

        <?php foreach ($_value as $_item) : ?>

        <?php if ($_item['static_text']) :?>
            var rowIndex = fieldControl.addStaticTextItem('<?= $this->escapeQuote($_item['header'], true); ?>', '<?= $this->escapeQuote($_item['static_text'], true); ?>');
        <?php else : ?>
            var rowIndex = fieldControl.addItem(
                '<?= $this->escapeQuote($_item['header'], true); ?>',
                '<?= $this->escapeQuote($_item['attribute'], true); ?>',
                '<?= $this->escapeQuote($_item['format'], true); ?>',
                '<?= $this->escapeQuote($_item['parent'], true); ?>'
            );
            <?php foreach($_item['modify'] as $_modify) : ?>

            fieldControl.modifyItem(rowIndex,
                '<?= $this->escapeQuote($_modify['modify'], true); ?>',
                '<?= $this->escapeQuote($_modify['arg0'], true); ?>',
                '<?= $this->escapeQuote($_modify['arg1'], true); ?>'
            );

            <?php endforeach; ?>

            fieldControl.showAddModifyLink(rowIndex);
        <?php endif; ?>

        <?php endforeach; ?>

        window.fieldControl = fieldControl;
        //]]>
    });
</script>
