<?php  
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile

$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$partner = $block->getProfileDetail();
if ($partner['shop_url'] && $helper->getSellerPolicyApproval()) {
    echo $partner['privacy_policy'];
}  ?>
