<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magestore\InventorySuccess\Block\Adminhtml\Order\Creditmemo\View\Items\Column\Warehouse */ ?>
<?php if ($_item = $block->getItem()): ?>
    <?php $warehouse = $block->getReturnWarehouse($_item) ?>
    <?php echo $this->getWarehouseDisplay($warehouse) ?>
<?php endif; ?>
