<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Feed
 */
?>
<?php
    $value       = $block->getElement()->getValue();
    $htmlId      = $block->getElement()->getHtmlId();
    $htmlClass   = $block->getElement()->getClass();
    $htmlName    = $block->getElement()->getName();
    $htmlNote    = $block->getElement()->getNote();
    $readonly    = $block->getElement()->getReadonly();
?>
<?php if ($htmlNote): ?>
    <p><?php echo $htmlNote->getText() ?></p>
<?php endif; ?>
<table class="data border data-grid">
    <thead>
        <tr>
            <th class="data-grid-th _sortable not-sort"><?php echo __('Header'); ?></th>
            <th class="data-grid-th _sortable not-sort"><?php echo __('Attribute'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($value as $idx => $element): ?>
        <tr>
            <td>
                <div><?php echo $element->getName();?></div>
                <small><?php echo $element->getDescription();?></small>
            </td>
            <td>
                <?php if ($idx !== 'condition'): ?>
                    <select name="<?php echo $htmlName; ?>[<?php echo $idx?>][attribute]" id="amasty_feed_content_attributes_<?php echo $idx;?>">
                        <?php if (!$element->getRequired()): ?>
                            <option value=''><?php echo __('None')?></option>
                        <?php endif;?>
                        <?php foreach ($this->getAttributes() as $type => $config): ?>
                            <?php $label = $config['label'];?>
                            <optgroup label="<?php echo $label;?>">
                                <?php foreach($config['options'] as $value => $label): ?>
                                    <?php $selected = $this->isSelectedAttribute($element, $value);?>
                                    <option <?php echo $selected ? 'selected' : '' ?> value="<?php echo $value ?>"><?php echo $block->escapeHtml($label) ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                        <?php endforeach; ?>
                    </select>
                <?php else: ?>
                    <input type="text" value="<?php echo $element->getValue(); ?>" name="<?php echo $htmlName; ?>[<?php echo $idx?>][attribute]" id="amasty_feed_content_attributes_<?php echo $idx;?>"/>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
