<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomOrderNumber
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

?>
<?php 
/**
 * @var $block \Bss\CustomOrderNumber\Block\System\Config\ResetInvoice
 */
?>
<?php if ($block->isInvoiceEnable($block->getRequest()->getParam('store', 0))) { ?>
    <script type="text/x-magento-init">
    {
        "*": 
        {
            "Bss_CustomOrderNumber/js/resetinvoice": {}
        }
    }
    </script>
<?php } ?>
<?php echo $block->getButtonHtml() ?>
<span id="invoice_span">
    <img class="processing" hidden="hidden" alt="" style="margin:0 5px"
         src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="success" hidden="hidden" alt="" style="margin:-3px 5px"
         src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <img class="error" hidden="hidden" alt="" style="margin:-1px 3px"
         src="<?php echo $block->getViewFileUrl('images/rule_component_remove.gif') ?>"/>
    <span id="invoice_message"></span>
    <span id="urlInvoice" hidden="hidden"><?php echo $block->getAjaxUrl() ?></span>
    <span id="storeIdInv" hidden="hidden"><?php echo $block->getRequest()->getParam('store', 0) ?></span>
</span>