<?php  
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile

$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$bannerDisplay      =   $helper->getDisplayBannerLayout3();
$bannerImage        =   $helper->getBannerImageLayout3();
$bannerContent      =   $helper->getBannerContentLayout3();
$marketplacebutton  =   $helper->getBannerButtonLayout3();
$marketplacelabel1  =   $helper->getMarketplacelabel1Layout3(); 
$marketplacelabel2  =   $helper->getMarketplacelabel2Layout3(); 
$marketplacelabel3  =   $helper->getMarketplacelabel3Layout3(); 
$iconsDisplay       =   $helper->getDisplayIconLayout3();
$iconImage1         =   $helper->getIconImage1Layout3();
$iconImage1Label    =   $helper->getIconImageLabel1Layout3();
$iconImage2         =   $helper->getIconImage2Layout3();
$iconImage2Label    =   $helper->getIconImageLabel2Layout3();
$iconImage3         =   $helper->getIconImage3Layout3();
$iconImage3Label    =   $helper->getIconImageLabel3Layout3();
$iconImage4         =   $helper->getIconImage4Layout3();
$iconImage4Label    =   $helper->getIconImageLabel4Layout3();
$iconImage5         =   $helper->getIconImage5Layout3();
$iconImage5Label    =   $helper->getIconImageLabel5Layout3();
$iconSeperatorImage = $this->getViewFileUrl('Webkul_Marketplace::images/landingpage2/icon/sell-page-2-arrow-right.png');
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getViewFileUrl('Webkul_Marketplace::css/landingpage_two.css');?>">
<div class="wk-mp-design wk-mp-landingpage wk-mp-landingpage-layout3">
    <?php
    if($bannerDisplay){?>
        <div class="wk-mp-banner-container-layout2">	
            <div class="wk-mp-banner">
                <div class="wk-list-container wk-mp-header">
                    <div class="wk-mp-header-container">
                        <?php echo $block->getCmsFilterContent($bannerContent)?>
                    </div>
                </div>
                <?php
                $sellerAccountUrl = $block->getUrl(
                    'marketplace/account/becomeseller',
                    ["_secure" => $this->getRequest()->isSecure()]
                );
                ?>
                <?php if (!$helper->isCustomerLoggedIn()): ?>
                    <?php $sellerAccountUrl = '#register-as-seller';?>
                    <div class="wk-list-container">
                        <div class="wk-list-container-registration wk-text-transform-left" id="register-as-seller">
                            <div class="wk-list-container-feature-label"><?php echo __('Register As Seller')?></div>
                            <?php echo $block->getChildHtml('customer_form_register_layout3');?>
                        </div>
                    </div>
            <?php endif; ?>
            </div>
        </div>
    <?php
    } ?>
    <h1 class="wk-marketplace-label"><?php echo $marketplacelabel1 ?></h1>
    <?php
    if($iconsDisplay){?>
        <div class="wk-mp-icon-container">
            <div class="wk-mp-icon-wraper">
                <div class="wk-mp-icon">
                    <img src="<?php echo $iconImage1 ?>">
                </div>
                <span class="wk-marketplace-label-span"><?php echo $iconImage1Label ?></span>
            </div>
            <div class="wk-mp-icon-seperator">
                <div class="wk-mp-icon">
                    <img src="<?php echo $iconSeperatorImage ?>">
                </div>
            </div>
            <div class="wk-mp-icon-wraper">
                <div class="wk-mp-icon">
                    <img src="<?php echo $iconImage2 ?>">
                </div>
                <span class="wk-marketplace-label-span"><?php echo $iconImage2Label ?></span>
            </div>
            <div class="wk-mp-icon-seperator">
                <div class="wk-mp-icon">
                    <img src="<?php echo $iconSeperatorImage ?>">
                </div>
            </div>
            <div class="wk-mp-icon-wraper">
                <div class="wk-mp-icon">
                    <img src="<?php echo $iconImage3 ?>">
                </div>
                <span class="wk-marketplace-label-span"><?php echo $iconImage3Label ?></span>
            </div>
            <div class="wk-mp-icon-seperator">
                <div class="wk-mp-icon">
                    <img src="<?php echo $iconSeperatorImage ?>">
                </div>
            </div>
            <div class="wk-mp-icon-wraper">
                <div class="wk-mp-icon">
                    <img src="<?php echo $iconImage4 ?>">
                </div>
                <span class="wk-marketplace-label-span"><?php echo $iconImage4Label ?></span>
            </div>
            <div class="wk-mp-icon-seperator">
                <div class="wk-mp-icon">
                    <img src="<?php echo $iconSeperatorImage ?>">
                </div>
            </div>
            <div class="wk-mp-icon-wraper">
                <div class="wk-mp-icon">
                    <img src="<?php echo $iconImage5 ?>">
                </div>
                <span class="wk-marketplace-label-span"><?php echo $iconImage5Label ?></span>
            </div>
        </div>
    <?php
    } ?>

    <h1 class="wk-marketplace-label flamh1"><?php echo $marketplacelabel2 ?></h1>

<!--    <div class="wk-list-container-wrapper wk-text-transform-left">
        <div class="wk-layout2-box-container" title="">
            <span class="wk-layout2-box-span-container"><?php echo __('Happiness is contagious pass it on');?></span>
            <span class="wk-layout2-box-span">
                <span class="wk-layout2-box-span-image"></span>
            </span>
            <div class="wk-icon-div"><?php echo __('Giving a gift is a powerful pathway for creating more personal joy.');?></div>
        </div>
        <div class="wk-layout2-box-container" title="">
            <span class="wk-layout2-box-span-container"><?php echo __('Why do people shop with us?');?></span>
            <span class="wk-layout2-box-span">
                <span class="wk-layout2-box-span-image wk-layout2-box-span-image-ask"></span>
            </span>
            <div class="wk-icon-div"><?php echo __('We offer something different. Something you won’t find elsewhere.');?></div>
        </div>
        <div class="wk-layout2-box-container" title="">
            <span class="wk-layout2-box-span-container"><?php echo __('Why sell with us?');?></span>
            <span class="wk-layout2-box-span">
                <span class="wk-layout2-box-span-image wk-layout2-box-span-image-quickpay"></span>
            </span>
            <div class="wk-icon-div"><?php echo __('We are a passionate fun bunch of individuals that want to spread happiness across the UAE. We are more than just a gift site.');?></div>
        </div>


        <div class="wk-layout2-box-container" title="" >
            <span class="wk-layout2-box-span-container"><?php echo __('How Flamingaroo works for our vendors:');?></span>
            <span class="wk-layout2-box-span">
                <span class="wk-layout2-box-span-image wk-layout2-box-span-image-order"></span>
            </span>
            <div class="wk-icon-div"><?php echo __('We will help you get set up – from product photography
partnership with Stu Williamson to setting up your own shop and
fulfillment of your orders.');?></div>
        </div>
        <div class="wk-layout2-box-container" title="" >
            <span class="wk-layout2-box-span-container"><?php echo __('How Flamingaroo works for our customers:');?></span>
            <span class="wk-layout2-box-span">
                <span class="wk-layout2-box-span-image wk-layout2-box-span-image-badges"></span>
            </span>
            <div class="wk-icon-div"><?php echo __('When you are shopping on Flamingaroo you are given the choice of the
most unusual gifts in the UAE made by local providers.');?></div>
        </div>
        <div class="wk-layout2-box-container" title="">
            <span class="wk-layout2-box-span-container"><?php echo __('Order processing and deliveries');?></span>
            <span class="wk-layout2-box-span">
                <span class="wk-layout2-box-span-image wk-layout2-box-span-image-verified"></span>
            </span>
            <div class="wk-icon-div"><?php echo __('Delivery is charged per item as per the standard delivery charges with
the UAE. Typically this is between 30-50AED per item.');?></div>
        </div>

        <div class="wk-layout2-box-container" title="Flamingaroo act as the payment agent between you and your customer.Any refunds will be adjusted in the monthly">
            <span class="wk-layout2-box-span-container"><?php echo __('Vendor payments');?></span>
            <span class="wk-layout2-box-span">
                <span class="wk-layout2-box-span-image wk-layout2-box-span-image-profile"></span>
            </span>
            <div class="wk-icon-div"><?php echo __('Flamingaroo act as the payment agent between you and your customer.
Any refunds will be adjusted in the monthly');?></div>
        </div>
        <div class="wk-layout2-box-container" title="">
            <span class="wk-layout2-box-span-container"><?php echo __('Returns and refunds');?></span>
            <span class="wk-layout2-box-span">
                <span class="wk-layout2-box-span-image wk-layout2-box-span-image-media"></span>
            </span>
            <div class="wk-icon-div"><?php echo __('Each vendor will have their own return policy, which should be stated on their page.');?></div>
        </div>
    </div> -->
    <div class="wk-list-container-wrapper wk-text-transform-center flamsellerdesc">
        <span class="wk-icon-check-span"><?php echo $marketplacelabel3 ?></span>
        <div class="primary" style="display:none;">
            <a href="<?php echo $sellerAccountUrl?>">
                <button type="submit" class="action submit primary" title="<?php echo $marketplacebutton; ?>">
                    <span><?php echo $marketplacebutton; ?></span>
                </button>
            </a>
        </div>
    </div>
</div>
<script>
    require([
        "jquery",
        "mage/mage",
    ], function($){
        $('.page-title-wrapper').hide();
        $('.wk-mp-landingpage').insertBefore('#maincontent');
        $('.wk-mp-banner').css('background-image','url("<?php echo $bannerImage ?>")');
    });
</script>