<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile
?>
<img 
    src="<?php echo $block->getSellerStatisticsGraphUrl('feed_quality') ?>" 
    alt="<?php echo __('Quality Reviews')?>" 
    title="<?php echo __('Quality Reviews')?>" />