<?php
/**
 * Solwin Infotech
 * Solwin Ournews Extension
 *
 * @category   Solwin
 * @package    Solwin_Ournews
 * @copyright  Copyright © 2006-2016 Solwin (https://www.solwininfotech.com)
 * @license    https://www.solwininfotech.com/magento-extension-license/ 
 */
?>
<?php
$helper = $this->helper('Solwin\Ournews\Helper\Data');
$enable = $helper->getEnableModule();
$route = $helper->getConfig('newssection/newsgroup/route');
$baseUrl = $helper->getBaseUrlWithStoreCode();
if ($enable) {
    ?>
    <li class="Test-Class">  
        <a  href="<?php echo $baseUrl . $route ?>"><?php echo $block->escapeHtml($block->getLabel()) ?>  
            <?php echo($block->getCounter()) ? '<span class="counter qty">' . $block->escapeHtml($block->getCounter()) . '</span>' : ''; ?>  
        </a>  
    </li>
<?php
}