<?php
/**
 * Solwin Infotech
 * Solwin Ournews Extension
 *
 * @category   Solwin
 * @package    Solwin_Ournews
 * @copyright  Copyright © 2006-2016 Solwin (https://www.solwininfotech.com)
 * @license    https://www.solwininfotech.com/magento-extension-license/ 
 */
?>
<?php
$baseUrl = $this->getBaseUrlWithStoreCode();

$_helper = $this->helper('\Solwin\Ournews\Helper\Data');
$enable = $_helper->getConfig('newssection/newsgroup/active');
$route = $_helper->getConfig('newssection/newsgroup/route');
$newsnotfound = $_helper->getConfig('newssection/newsgroup/newsnotfound');
$blocktitle = $_helper->getConfig('newssection/newsgroup/newstitle');
$readmoretitle = $_helper->getConfig('newssection/newsgroup/readmore');

if ($enable) {
    ?>
    <div class="block block-news">
        <div class="block-title">
            <strong><?php echo $blocktitle; ?></strong>
        </div>
        <div class="block-content">
            <?php
            $newslimit = $_helper->getConfig('newssection/newsgroup/newslimit');
            $collection = $this->getNewsCollection($newslimit);
            $size = $collection->getSize();

            if ($size > 0) {
                ?>
                <?php foreach ($collection as $newsData): ?>
                    <?php
                    ?>
                    <p class="sidevar-news"><a href='<?php echo $newsData->getViewUrl(); ?>'><?php echo $newsData->getTitle(); ?></a></p>
                <?php endforeach; ?>
                <div class="read-more-sidebar">
                    <a href="<?php echo $baseUrl . $route; ?>"><?php echo $readmoretitle; ?></a>
                </div>
            <?php } else { ?>
                <div class="empty"><?php echo $newsnotfound; ?></div>
            <?php } ?>
        </div>
    </div>

<?php
}