<?php
/**
 * Solwin Infotech
 * Solwin Ournews Extension
 *
 * @category   Solwin
 * @package    Solwin_Ournews
 * @copyright  Copyright © 2006-2016 Solwin (https://www.solwininfotech.com)
 * @license    https://www.solwininfotech.com/magento-extension-license/
 */
?>
<?php

$baseUrl = $this->getBaseUrlWithStoreCode();
$mediaPath = $this->getMediaPath();
$mediaUrl = $this->getBaseUrl() . 'pub/media/';
$imageUrl = $mediaUrl.'solwin/ournews/news/image';
$currId = $this->getRequest()->getParam('id');
$_helper = $this->helper('\Solwin\Ournews\Helper\Data');
$enable = $_helper->getConfig('newssection/newsgroup/active');
$route = $_helper->getConfig('newssection/newsgroup/route');
$newsnotfound = $_helper->getConfig('newssection/newsgroup/newsnotfound');

$defImage = $this->getDefaultImage();
?>
<?php
if ($enable) {
    if ($currId != '') {
        // load news collection by news_id
        $collection = $this->getSingleNewsCollection($currId);
        $title = $collection->getTitle();
        $shortdesc = $collection->getShortdesc();
        $description = $collection->getDescription();
        $url = $collection->getUrl();
        $publish_date = $collection->getStartPublishDate();
        ?>
        <div class = "ournews-view">
            <div class = "ournews-detail">
                <div class = "news-block-left">
                    <?php
                    $imageURL = $defImage;
                    $imageName = $collection->getImage();
                    if ($imageName != '') {
                        $imagePath = $mediaPath.'solwin/ournews/news/image'.$imageName;
                        if (file_exists($imagePath)) {
                            $imageURL = $imageUrl . $imageName;
                        }
                    }
                    ?>
                    <img src="<?php echo $imageURL; ?>" alt="<?php echo $title; ?>" />
                </div>
                <div class="news-block-title"><?php echo $title; ?></div>
                <div class="news-block-right">
                    <?php if ($shortdesc != ''): ?>
                        <div class="ournews-description">
                            <?php echo $this->filterContent($shortdesc); ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($description != ''): ?>
                        <div class="ournews-description">
                            <?php echo $this->filterContent($description); ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($url != ''): ?>
                        <div class="ournews-url">
                            <a href="<?php echo $url; ?>"><?php echo $url; ?></a>
                        </div>
                    <?php endif; ?>
                    <?php if ($publish_date != ''): ?>
                        <div class="ournews-date">
                            <b>Published on : </b><?php echo date('d M, Y', strtotime($publish_date)); ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="back-btn">
            <a class="read-more action primary" href="<?php echo $baseUrl . $route; ?>" title="All News">
                <?php echo __('All News'); ?>
            </a>
        </div>
        <?php
    } else {
        //get all news collection
        $collection = $this->getCollection();

        $size = $collection->getSize();

        if ($size > 0):
            ?>
            <div class="ournews-list-container">
                <?php //echo $this->getPagerHtml();      ?>
                <div class="news-wrapper">
                    <?php foreach ($collection as $newsData): ?>
                        <div class="ournews-list-item">
                            <div class="news-left">
                                <?php
                                $imageURL = $defImage;
                                $imageName = $newsData->getImage();
                                if ($imageName != '') {
                                    $imagePath = $mediaPath.'solwin/ournews/news/image'.$imageName;
                                    if (file_exists($imagePath)) {
                                        $imageURL = $imageUrl . $imageName;
                                    }
                                }

                                ?>
                                <a href="<?php echo $newsData->getViewUrl(); ?>">
                                    <img class="member_avatar" src="<?php echo $imageURL; ?>" alt="<?php echo $newsData->getName(); ?>"/>
                                </a>
                            </div>
                            <div class="news-right">
                                <h2>
                                    <a href="<?php echo $newsData->getViewUrl(); ?>">
                                        <?php echo $newsData->getTitle(); ?>
                                    </a>
                                </h2>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    <?php ?>
                </div>
                <?php
                if ($this->getPagerHtml()) {
                    echo $this->getPagerHtml();
                }
                ?>
            </div>
        <?php else : ?>
            <div class="message info empty">
                <div><?php echo $newsnotfound; ?></div>
            </div>
        <?php
        endif;
    }
} ?>
<style>
.ournews-index-index .page-main > .page-title-wrapper .page-title {
    display :none !important;
}
</style>