<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>
<?php
$_helper = $this->helper('Webapp\Lazyload\Helper\Data');
$imgSrc = $_helper->getImageLoader();
$imgDataOriginal = $block->getImageUrl();
?>
<img class="img-responsive lazy"
     <?php /* @escapeNotVerified */ echo $block->getCustomAttributes(); ?>
     src="<?php /* @escapeNotVerified */ echo $imgSrc; ?>"
     data-original="<?php /* @escapeNotVerified */ echo $imgDataOriginal; ?>"
     width="<?php /* @escapeNotVerified */ echo $block->getWidth(); ?>"
     height="<?php /* @escapeNotVerified */ echo $block->getHeight(); ?>"
     alt="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getLabel(), null, true); ?>" />