<?php  
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile

$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$pageLayout  =	$helper->getPageLayout();
if ($pageLayout == 1) {
	echo $block->getChildHtml('landingPagelayout1');
} else if ($pageLayout == 2) {
	echo $block->getChildHtml('landingPagelayout2');
} else {
	echo $block->getChildHtml('landingPagelayout3');
}